name: Workflow Demo

on: 
  push

env:
  ACCESS_ID: ${{ vars.ACCESS_ID }}

jobs: 
  build: #new job added
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: echo $ACCESS_ID
